name: Build and Push Docker Images
# name: Build Docker Images and Binaries

# reusable workflow, do not add triggers
on:
  workflow_call:
  workflow_dispatch:

env:
  GHCR: ghcr.io/${{ github.repository }}

jobs:
  build-docker:
    name: main
    permissions:
      id-token: write
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        runner:
          - selector: ubuntu-latest
            platform: linux/amd64
          - selector: burnt-labs-arm64
            platform: linux/arm64
    runs-on: ${{ matrix.runner.selector }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx for push
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
          platforms: ${{ matrix.runner.platform }}

      - name: Metadata for container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR }}/xion
          tags: |
            type=sha

      - name: Prepare environment
        run: |
          PLATFORM=$(echo ${{ matrix.runner.platform }} | sed 's/\//-/g')
          echo "PLATFORM=${PLATFORM}" | tee -a $GITHUB_ENV
          echo "XIOND_FN=xiond-$PLATFORM" | tee -a $GITHUB_ENV
          echo "DOCKER_FN=docker-$PLATFORM.tar" | tee -a $GITHUB_ENV
          echo "HEIGHLINER_FN=heighliner-$PLATFORM.tar" | tee -a $GITHUB_ENV
          echo "VERSION=$(git describe --tags | sed 's/^v//')" | tee -a $GITHUB_ENV
          echo "TAG_VERSION=${GITHUB_SHA:0:7}" | tee -a $GITHUB_ENV

      - name: Build Docker Image
        id: build-docker
        uses: docker/build-push-action@v5
        with:
          build-args: |
            COMMIT=${{ github.sha }}
            VERSION=${{ env.VERSION }}
            TAG_VERSION=${{ env.TAG_VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.runner.platform }}
          push: false
          target: release
          outputs: type=docker,name=${{ env.GHCR }}/xion,name-canonical=true

      - name: Build Heighliner Image
        id: build-heighliner
        uses: docker/build-push-action@v5
        with:
          build-args: |
            BASE_IMAGE=${{ env.GHCR }}/xion
            VERSION=${{ env.TAG_VERSION }}
            BINARIES=/usr/bin/xiond
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.runner.platform }}
          target: heighliner
          outputs: type=docker,name=${{ env.GHCR }}/heighliner,name-canonical=true

      - name: Save Docker Image
        working-directory: ${{ runner.temp }}
        run: |
          docker save ${{ env.GHCR }}/xion > ${{ env.DOCKER_FN }}

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DOCKER_FN }}
          path: ${{ runner.temp }}/${{ env.DOCKER_FN }}
          if-no-files-found: error
          retention-days: 3

      - name: Save Heighliner Image
        working-directory: ${{ runner.temp }}
        run: |
          docker save ${{ env.GHCR }}/heighliner > ${{ env.HEIGHLINER_FN }}

      - name: Upload Heighliner Image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.HEIGHLINER_FN }}
          path: ${{ runner.temp }}/${{ env.HEIGHLINER_FN }}
          if-no-files-found: error
          retention-days: 3

      - name: Copy xiond binary from container
        # if-contains(github.event.ref, 'v[0-9]+\.[0-9]+\.[0-9]+')
        working-directory: ${{ runner.temp }}
        run: |
          tmpname=ctr-${{ env.XIOND_FN }}
          docker create --platform ${{ matrix.runner.platform }} --name ${tmpname} ${{ env.GHCR }}/xion
          docker cp ${tmpname}:/usr/bin/xiond ${{ env.XIOND_FN }}
          docker rm -v ${tmpname}

      - name: Upload binary
        # if-contains(github.event.ref, 'v[0-9]+\.[0-9]+\.[0-9]+')
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.XIOND_FN }}
          path: ${{ runner.temp }}/${{ env.XIOND_FN }}
          retention-days: 3
