name: Interchain tests

# reusable workflow, do not add triggers
on:
  workflow_call:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GHCR: ghcr.io/${{ github.repository }}

jobs:
  build-integration-tests:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - burnt-labs-amd64
          - burnt-labs-arm64
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Prepare Environment
        run: |
          sed -En 's/^go (.*)$/GO_VERSION=\1/p' go.mod | tee -a $GITHUB_ENV
          echo "PLATFORM=$(echo ${{ matrix.runner }} | cut -d- -f2-)" | tee -a $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ^${{ env.GO_VERSION }}

      - name: build go test binary
        working-directory: integration_tests
        run: |
          go test -c

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLATFORM }}/test
          path: integration_tests/integration_tests.test
          retention-days: 3

      - name: find wasmvm lib
        run: echo "WASM_PATH=$(find /home/runner/go/pkg/mod -name libwasmvm.x86_64.so 2>/dev/null | head -n 1)" >> $GITHUB_ENV

      - name: Upload wasmvm lib
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLATFORM }}/libwasmvm.x86_64.so
          path: ${{ env.WASM_PATH }}
          retention-days: 3

  interchain-tests:
    runs-on: ${{ matrix.runner }}
    needs: build-integration-tests
    strategy:
      fail-fast: false
      matrix:
        runner:
          - burnt-labs-amd64
          - burnt-labs-arm64
        test_type:
        - "DungeonTransferBlock"
        - "XionSendPlatformFee"
        - "MintModuleNoInflationNoFees"
        - "MintModuleInflationHighFees"
        - "MintModuleInflationLowFees"
        - "JWTAbstractAccount"
        - "XionSendPlatformFee"
        - "XionAbstractAccount"
        - "WebAuthNAbstractAccount"
        - "XionMinimumFeeDefault"
        - "XionMinimumFeeZero"
        - "XionTokenFactory"
        - "XionAbstractAccountJWTCLI"
        - "TreasuryContract"
        - "TreasuryMulti"
        - "SingleAbstractAccountMigration"

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Prepare Environment
        run: |
          echo "PLATFORM=$(echo ${{ matrix.runner }} | cut -d- -f2-)" | tee -a $GITHUB_ENV

      - name: Download integration test binary
        uses: actions/download-artifact@v4
        with:
          path: integration_tests
          pattern: ${{ env.PLATFORM }}/test
          merge-multiple: true

      - name: Download wasm vm lib
        uses: actions/download-artifact@v4
        with:
          path: integration_tests
          pattern: ${{ env.PLATFORM }}/libwasmvm.x86_64.so
          merge-multiple: true

      - name: Download heighliner images
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}
          pattern: heighliner*
          merge-multiple: true

      - name: Load images
        working-directory: ${{ runner.temp }}
        run: |
          for image in heighliner*.tar; do docker load < $image; done;

      - name: Run all up ci test
        run: |
          chmod a+x ./integration_tests/integration_tests.test
          ./integration_tests/integration_tests.test -test.failfast -test.v -test.run Test${{ matrix.test_type }}
        env:
          E2E_SKIP_CLEANUP: true
          XION_IMAGE: ${{ env.GHCR }}/xion
